services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    SchoolIT\CommonBundle\Controller\:
        resource: '../../Controller'
        exclude: '../../Controller/Model'
        tags:
            - 'controller.service_arguments'

    SchoolIT\CommonBundle\Controller\LogoutController:
        arguments:
            $logoutUrl: '%env(IDP_LOGOUT_URL)%'
