services:
  _defaults:
      autowire: true
      public: false

  SchulIT\CommonBundle\Store\IdStore:
    arguments:
      $timeProvider: "@lightsaml.system.time_provider"

  SchulIT\CommonBundle\Security\Factory\SamlSpTokenFactory: ~

