services:
  _defaults:
      public: false
      autowire: true

  _instanceof:
      Twig_ExtensionInterface:
          tags: ['twig.extension']

      Symfony\Component\EventDispatcher\EventSubscriberInterface:
          tags: ['kernel.event_subscriber']

  SchoolIT\CommonBundle\Twig\CommonExtension:
    arguments:
      $menuService: "%app.common.menu%"

  SchoolIT\CommonBundle\Twig\ConfigVariable:
    arguments:
      - "%app.common.name%"
      - "%app.common.host%"
      - "%app.common.path%"
      - "%app.common.ssl%"
      - "%app.common.version%"
      - "%app.common.project_url%"
      - "%app.common.logo%"

  # Event Listener
  SchoolIT\CommonBundle\EventListener\LocaleListener:
    arguments:
      $locales: '%app.common.locales%'

  SchoolIT\CommonBundle\EventListener\ConsoleListener:
    calls:
      - [ "setContainer", ["@service_container"]]

  # DateHelper
  SchoolIT\CommonBundle\Helper\DateHelper: ~

  # Monolog
  SchoolIT\CommonBundle\Monolog\DatabaseHandler:
    arguments:
      $connection: "@doctrine.dbal.default_connection"
