services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  SchulIT\CommonBundle\SwiftMailer\EmailSpoolHelper:
    arguments:
      - "%swiftmailer.spool.default.file.path%"

  SchulIT\CommonBundle\SwiftMailer\EmailListener:
    arguments:
      - "@monolog.logger.mailer"
    tags:
      - { name: monolog.logger, channel: mailer }
      - { name: "swiftmailer.default.plugin"}

  SchulIT\CommonBundle\Controller\MailController:
    tags:
      - 'controller.service_arguments'

  SchulIT\CommonBundle\Command\SendMailsCommand:
    tags:
      - { name: shapecode_cron.cron_job, expression: '* *\/2 * * *' }
