services:
  SchoolIT\CommonBundle\SwiftMailer\EmailSpoolHelper:
    arguments:
    - "%swiftmailer.spool.default.file.path%"

  SchoolIT\CommonBundle\SwiftMailer\EmailListener:
    arguments:
    - "@monolog.logger.mailer"
    public: false
    tags:
    - { name: monolog.logger, channel: mailer }
    - { name: "swiftmailer.default.plugin"}
