services:
  SchulIT\CommonBundle\SwiftMailer\EmailSpoolHelper:
    arguments:
      - "%swiftmailer.spool.default.file.path%"

  SchulIT\CommonBundle\SwiftMailer\EmailListener:
    arguments:
      - "@monolog.logger.mailer"
    public: false
    tags:
      - { name: monolog.logger, channel: mailer }
      - { name: "swiftmailer.default.plugin"}

  SchulIT\CommonBundle\Controller\MailController:
    autowire: true
    autoconfigure: true
    public: false
    tags:
      - 'controller.service_arguments'
